spring:
  application:
    name: financial-management

  datasource:
    url: jdbc:postgresql://localhost:5432/financial?useTimezone=true&serverTimezone=UTC
    username: carlos.albertof
    password: c@F#317955

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  spring-doc:
    paths-to-match: /financial/**/**
    swagger-ui:
      use-root-path: true